/********************************************************************************************
*					GestPymeSOC - DataBase Constraints Creation
* +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
* Convencion de Nombramiento de constraints
* [ABREVIACION_TABLA]_[ABREVIACION_CAMPOS_IMPLICADOS]_[SUFIJO]
*
* Sufijos Validos:
* FOREIGN KEY:		_FK
* UNIQUE:			_UK
* CHECK:			_CK
* PRIMARY KEY:		_PK
*
* Ejemplo: Tabla SGT_USUARIOS tiene un campo llamado LOGIN_ALIAS que debe ser UNICO
*
* El constraint se llamaria asi:
* ABREVIACION TABLA: USRS
* ABREVIACION_CAMPOS_IMPLICADOS: LOGIN
* SUFIJO: _UK
*
* Resultado: USRS_LOGIN_UK
*
*********************************************************************************************/


/**************************************************************************************************************************************
* Creacion de Constraints para tabla GPT_CARGOS
**************************************************************************************************************************************/
ALTER TABLE GESTPYMESOC.GPT_CARGOS ADD CONSTRAINT CARGOS_COD_UK UNIQUE(COD_CARGO);


/**************************************************************************************************************************************
* Creacion de Constraints para tabla GPT_MOTIVOS_TERMINAC_CONTRATO
**************************************************************************************************************************************/
ALTER TABLE GESTPYMESOC.GPT_MOTIVOS_TERMINAC_CONTRATO ADD CONSTRAINT MOT_TERMI_OBLIDEMN_CK CHECK(OBLIGA_INDEMNIZACION IN('N','S'));


/**************************************************************************************************************************************
* Creacion de Constraints para tabla GPT_EMPLEADOS
**************************************************************************************************************************************/
ALTER TABLE GESTPYMESOC.GPT_EMPLEADOS ADD CONSTRAINT EMPL_CIUDAD_FK FOREIGN KEY (ID_CIUDAD) REFERENCES MATCENTRAL.MAT_CIUDADES (ID_CIUDAD) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GESTPYMESOC.GPT_EMPLEADOS ADD CONSTRAINT EMPL_TIPO_CONTR_FK FOREIGN KEY (ID_TIPO_CONTRIBUYENTE) REFERENCES MATCENTRAL.MAT_TIPOS_CONTRIBUYENTE (ID_TIPO_CONTRIBUYENTE) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GESTPYMESOC.GPT_EMPLEADOS ADD CONSTRAINT EMPL_ACT_ECONOM_FK FOREIGN KEY (ID_ACTIVIDAD_ECONOMICA) REFERENCES MATCENTRAL.MAT_ACTIVIDADES_ECONOMICAS (ID_ACTIVIDAD_ECONOMICA) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GESTPYMESOC.GPT_EMPLEADOS ADD CONSTRAINT EMPL_TIPO_ID_FK FOREIGN KEY (ID_TIPO_IDENTIFICACION) REFERENCES MATCENTRAL.MAT_TIPOS_IDENTIFICACION (ID_TIPO_IDENTIFICACION) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GESTPYMESOC.GPT_EMPLEADOS ADD CONSTRAINT EMPL_TIPO_PERS_CK CHECK (COD_TIPO_PERSONA IN('PERSONA_NATURAL','PERSONA_JURIDICA'));
ALTER TABLE GESTPYMESOC.GPT_EMPLEADOS ADD CONSTRAINT EMPL_NUMIDENT_UK UNIQUE(NUM_IDENTIFICACION);
ALTER TABLE GESTPYMESOC.GPT_EMPLEADOS ADD CONSTRAINT EMPL_EPS_FK FOREIGN KEY (ID_EPS) REFERENCES MATCENTRAL.MAT_EPSS (ID_EPS) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GESTPYMESOC.GPT_EMPLEADOS ADD CONSTRAINT EMPL_AFP_FK FOREIGN KEY (ID_AFP) REFERENCES MATCENTRAL.MAT_AFPS (ID_AFP) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GESTPYMESOC.GPT_EMPLEADOS ADD CONSTRAINT EMPL_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES MATCENTRAL.MAT_ESTADOS (ID_ESTADO) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GESTPYMESOC.GPT_EMPLEADOS ADD CONSTRAINT EMPL_GENERO_FK FOREIGN KEY (ID_GENERO) REFERENCES MATCENTRAL.MAT_DATOS_MAESTRAS (ID_DATO_MAESTRA) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GESTPYMESOC.GPT_EMPLEADOS ADD CONSTRAINT EMPL_PROFESION_FK FOREIGN KEY (ID_PROFESION) REFERENCES MATCENTRAL.MAT_DATOS_MAESTRAS (ID_DATO_MAESTRA) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GESTPYMESOC.GPT_EMPLEADOS ADD CONSTRAINT EMPL_EMPR_FK FOREIGN KEY (ID_EMPRESA) REFERENCES MATCENTRAL.MAT_EMPRESAS (ID_EMPRESA) ON UPDATE NO ACTION ON DELETE NO ACTION;


/**************************************************************************************************************************************
* Creacion de Constraints para tabla GPT_CONTRATOS_LABORALES
**************************************************************************************************************************************/
ALTER TABLE GESTPYMESOC.GPT_CONTRATOS_LABORALES ADD CONSTRAINT CONTRAT_EMPRESA_FK FOREIGN KEY (ID_EMPRESA) REFERENCES MATCENTRAL.MAT_EMPRESAS (ID_EMPRESA) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GESTPYMESOC.GPT_CONTRATOS_LABORALES ADD CONSTRAINT CONTRAT_EMPLEADO_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES GESTPYMESOC.GPT_EMPLEADOS (ID_TERCERO) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GESTPYMESOC.GPT_CONTRATOS_LABORALES ADD CONSTRAINT CONTRAT_CARGO_FK FOREIGN KEY (ID_CARGO) REFERENCES GESTPYMESOC.GPT_CARGOS (ID_CARGO) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GESTPYMESOC.GPT_CONTRATOS_LABORALES ADD CONSTRAINT CONTRAT_MOTIVOTERM_FK FOREIGN KEY (ID_MOTIVO_TERMINACION) REFERENCES GESTPYMESOC.GPT_MOTIVOS_TERMINAC_CONTRATO (ID_MOTIVO_TERMINACION) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GESTPYMESOC.GPT_CONTRATOS_LABORALES ADD CONSTRAINT CONTRAT_ESVIGENT_CK CHECK(ES_VIGENTE IN('N','S'));
ALTER TABLE GESTPYMESOC.GPT_CONTRATOS_LABORALES ADD CONSTRAINT CONTRAT_ESSAL_INTEGR_CK CHECK(ES_SALARIO_INTEGRAL IN('N','S'));
ALTER TABLE GESTPYMESOC.GPT_CONTRATOS_LABORALES ADD CONSTRAINT CONTRAT_DERECH_RECARG_CK CHECK(DERECHO_RECARGOS IN('N','S'));
ALTER TABLE GESTPYMESOC.GPT_CONTRATOS_LABORALES ADD CONSTRAINT CONTRAT_REPORTT_RECARG_CK CHECK(REPORTA_TIEMPO IN('N','S'));
ALTER TABLE GESTPYMESOC.GPT_CONTRATOS_LABORALES ADD CONSTRAINT CONTRAT_TIPOTERMINO_CK CHECK(DERECHO_RECARGOS IN('FIJO','INDEFINIDO'));


/**************************************************************************************************************************************
* Creacion de Constraints para tabla GPT_PROVEEDORES
**************************************************************************************************************************************/
ALTER TABLE GESTPYMESOC.GPT_PROVEEDORES ADD CONSTRAINT PROV_CIUDAD_FK FOREIGN KEY (ID_CIUDAD) REFERENCES MATCENTRAL.MAT_CIUDADES (ID_CIUDAD) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GESTPYMESOC.GPT_PROVEEDORES ADD CONSTRAINT PROV_TIPO_CONTR_FK FOREIGN KEY (ID_TIPO_CONTRIBUYENTE) REFERENCES MATCENTRAL.MAT_TIPOS_CONTRIBUYENTE (ID_TIPO_CONTRIBUYENTE) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GESTPYMESOC.GPT_PROVEEDORES ADD CONSTRAINT PROV_ACT_ECONOM_FK FOREIGN KEY (ID_ACTIVIDAD_ECONOMICA) REFERENCES MATCENTRAL.MAT_ACTIVIDADES_ECONOMICAS (ID_ACTIVIDAD_ECONOMICA) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GESTPYMESOC.GPT_PROVEEDORES ADD CONSTRAINT PROV_TIPO_ID_FK FOREIGN KEY (ID_TIPO_IDENTIFICACION) REFERENCES MATCENTRAL.MAT_TIPOS_IDENTIFICACION (ID_TIPO_IDENTIFICACION) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GESTPYMESOC.GPT_PROVEEDORES ADD CONSTRAINT PROV_TIPO_PERS_CK CHECK (COD_TIPO_PERSONA IN('PERSONA_NATURAL','PERSONA_JURIDICA'));
ALTER TABLE GESTPYMESOC.GPT_PROVEEDORES ADD CONSTRAINT PROV_NUMIDENT_UK UNIQUE(NUM_IDENTIFICACION);


/**************************************************************************************************************************************
* Creacion de Constraints para tabla GPT_CLIENTES
**************************************************************************************************************************************/
ALTER TABLE GESTPYMESOC.GPT_CLIENTES ADD CONSTRAINT CLI_CIUDAD_FK FOREIGN KEY (ID_CIUDAD) REFERENCES MATCENTRAL.MAT_CIUDADES (ID_CIUDAD) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GESTPYMESOC.GPT_CLIENTES ADD CONSTRAINT CLI_TIPO_CONTR_FK FOREIGN KEY (ID_TIPO_CONTRIBUYENTE) REFERENCES MATCENTRAL.MAT_TIPOS_CONTRIBUYENTE (ID_TIPO_CONTRIBUYENTE) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GESTPYMESOC.GPT_CLIENTES ADD CONSTRAINT CLI_ACT_ECONOM_FK FOREIGN KEY (ID_ACTIVIDAD_ECONOMICA) REFERENCES MATCENTRAL.MAT_ACTIVIDADES_ECONOMICAS (ID_ACTIVIDAD_ECONOMICA) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GESTPYMESOC.GPT_CLIENTES ADD CONSTRAINT CLI_TIPO_ID_FK FOREIGN KEY (ID_TIPO_IDENTIFICACION) REFERENCES MATCENTRAL.MAT_TIPOS_IDENTIFICACION (ID_TIPO_IDENTIFICACION) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GESTPYMESOC.GPT_CLIENTES ADD CONSTRAINT CLI_TIPO_PERS_CK CHECK (COD_TIPO_PERSONA IN('PERSONA_NATURAL','PERSONA_JURIDICA'));
ALTER TABLE GESTPYMESOC.GPT_CLIENTES ADD CONSTRAINT CLI_NUMIDENT_UK UNIQUE(NUM_IDENTIFICACION);


/**************************************************************************************************************************************
* Creacion de Constraints para tabla GPT_PERIODO_LIQUID_NOMINA
**************************************************************************************************************************************/
ALTER TABLE GESTPYMESOC.GPT_PERIODO_LIQUID_NOMINA ADD CONSTRAINT PERINOMI_EMPR_FK FOREIGN KEY (ID_EMPRESA) REFERENCES MATCENTRAL.MAT_EMPRESAS (ID_EMPRESA) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GESTPYMESOC.GPT_PERIODO_LIQUID_NOMINA ADD CONSTRAINT PERINOMI_EMPRFEC_UK UNIQUE(ID_EMPRESA,COD_TIPO_PERIODO_NOMINA,FEC_INICIO_PERIODO,FEC_FIN_PERIODO);
ALTER TABLE GESTPYMESOC.GPT_PERIODO_LIQUID_NOMINA ADD CONSTRAINT PERINOMI_RANGFECHAS_CK CHECK (FEC_INICIO_PERIODO < FEC_FIN_PERIODO);
ALTER TABLE GESTPYMESOC.GPT_PERIODO_LIQUID_NOMINA ADD CONSTRAINT PERINOMI_TIPOPERIO_CK CHECK (COD_TIPO_PERIODO_NOMINA IN('SEMANAL','QUINCENAL', 'MENSUAL'));
ALTER TABLE GESTPYMESOC.GPT_PERIODO_LIQUID_NOMINA ADD CONSTRAINT PERINOMI_ESLIQUID_CK CHECK (ES_LIQUIDADO IN('N','S'));


/**************************************************************************************************************************************
* Creacion de Constraints para tabla GPT_REPORTE_TIEMPO
**************************************************************************************************************************************/
ALTER TABLE GESTPYMESOC.GPT_REPORTE_TIEMPO ADD CONSTRAINT REPORTMP_PERIODO_FK FOREIGN KEY (ID_PERIODO_NOMINA) REFERENCES GESTPYMESOC.GPT_PERIODO_LIQUID_NOMINA (ID_PERIODO_NOMINA) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GESTPYMESOC.GPT_REPORTE_TIEMPO ADD CONSTRAINT REPORTMP_EMPLEADO_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES GESTPYMESOC.GPT_EMPLEADOS (ID_TERCERO) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GESTPYMESOC.GPT_REPORTE_TIEMPO ADD CONSTRAINT REPORTMP_RANGOHORA_CK CHECK(HORA_ENTRADA < HORA_SALIDA);
ALTER TABLE GESTPYMESOC.GPT_REPORTE_TIEMPO ADD CONSTRAINT REPORTMP_ESTURNO_CK CHECK(ES_TURNO IN('N','S'));
ALTER TABLE GESTPYMESOC.GPT_REPORTE_TIEMPO ADD CONSTRAINT REPORTMP_TIPTURNO_CK CHECK(COD_TIPO_TURNO IN('DIURNO','NOCTURNO'));
ALTER TABLE GESTPYMESOC.GPT_REPORTE_TIEMPO ADD CONSTRAINT REPORTMP_ESDESC_CK CHECK(ES_DESCANSO IN('N','S'));
