/********************************************************************************************
*					GestPymeSOC - DataBase Constraints Creation
* +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
* Convencion de Nombramiento de constraints
* [ABREVIACION_TABLA]_[ABREVIACION_CAMPOS_IMPLICADOS]_[SUFIJO]
*
* Sufijos Validos:
* FOREIGN KEY:		_FK
* UNIQUE:			_UK
* CHECK:			_CK
* PRIMARY KEY:		_PK
*
* Ejemplo: Tabla SGT_USUARIOS tiene un campo llamado LOGIN_ALIAS que debe ser UNICO
*
* El constraint se llamaria asi:
* ABREVIACION TABLA: USRS
* ABREVIACION_CAMPOS_IMPLICADOS: LOGIN
* SUFIJO: _UK
*
* Resultado: USRS_LOGIN_UK
*
*********************************************************************************************/


/**************************************************************************************************************************************
* Creacion de Constraints para tabla GPT_CARGOS
**************************************************************************************************************************************/
ALTER TABLE GPT_CARGOS ADD CONSTRAINT CARGOS_PK PRIMARY KEY (ID_CARGO);
ALTER TABLE GPT_CARGOS ADD CONSTRAINT CARGOS_COD_UK UNIQUE(COD_CARGO);


/**************************************************************************************************************************************
* Creacion de Constraints para tabla GPT_MOTIVOS_TERMINAC_CONTRATO
**************************************************************************************************************************************/
ALTER TABLE GPT_MOTIVOS_TERMINAC_CONTRATO ADD CONSTRAINT MOTIVOS_TERMINAC_CONTRATO_PK PRIMARY KEY (ID_MOTIVO_TERMINACION);
ALTER TABLE GPT_MOTIVOS_TERMINAC_CONTRATO ADD CONSTRAINT MOT_TERMI_OBLIDEMN_CK CHECK(OBLIGA_INDEMNIZACION IN('N','S'));


/**************************************************************************************************************************************
* Creacion de Constraints para tabla GPT_EMPLEADOS
**************************************************************************************************************************************/
ALTER TABLE GPT_EMPLEADOS ADD CONSTRAINT EMPLEADOS_PK PRIMARY KEY (ID_EMPLEADO);
ALTER TABLE GPT_EMPLEADOS ADD CONSTRAINT EMPL_IDTERC_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES MATCENTRAL.MAT_TERCEROS (ID_TERCERO) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GPT_EMPLEADOS ADD CONSTRAINT EMPL_EPS_FK FOREIGN KEY (ID_EPS) REFERENCES MATCENTRAL.MAT_EPSS (ID_EPS) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GPT_EMPLEADOS ADD CONSTRAINT EMPL_AFP_FK FOREIGN KEY (ID_AFP) REFERENCES MATCENTRAL.MAT_AFPS (ID_AFP) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GPT_EMPLEADOS ADD CONSTRAINT EMPL_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES MATCENTRAL.MAT_ESTADOS (ID_ESTADO) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GPT_EMPLEADOS ADD CONSTRAINT EMPL_GENERO_FK FOREIGN KEY (ID_GENERO) REFERENCES MATCENTRAL.MAT_DATOS_MAESTRAS (ID_DATO_MAESTRA) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GPT_EMPLEADOS ADD CONSTRAINT EMPL_PROFESION_FK FOREIGN KEY (ID_PROFESION) REFERENCES MATCENTRAL.MAT_DATOS_MAESTRAS (ID_DATO_MAESTRA) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GPT_EMPLEADOS ADD CONSTRAINT EMPL_EMPR_FK FOREIGN KEY (ID_EMPRESA) REFERENCES MATCENTRAL.MAT_EMPRESAS (ID_EMPRESA) ON UPDATE NO ACTION ON DELETE NO ACTION;


/**************************************************************************************************************************************
* Creacion de Constraints para tabla GPT_TIPOS_CONTRATO_LABORAL
**************************************************************************************************************************************/
ALTER TABLE GPT_TIPOS_CONTRATO_LABORAL ADD CONSTRAINT TIPOS_CONTRATO_PK PRIMARY KEY (ID_TIPO_CONTRATO);
ALTER TABLE GPT_TIPOS_CONTRATO_LABORAL ADD CONSTRAINT TIPOS_CONTR_APLICNOTIF_CK CHECK(APLICA_NOFICACION_TERMINACION IN('N','S'));
ALTER TABLE GPT_TIPOS_CONTRATO_LABORAL ADD CONSTRAINT TIPOS_CONTR_APLICEXTRAS_CK CHECK(APLICA_PAGO_EXTRAS IN('N','S'));
ALTER TABLE GPT_TIPOS_CONTRATO_LABORAL ADD CONSTRAINT TIPOS_CONTR_ESPRORROG_CK CHECK(ES_PRORROGABLE IN('N','S'));
ALTER TABLE GPT_TIPOS_CONTRATO_LABORAL ADD CONSTRAINT TIPOS_CONTR_PERIOPRUEBAS_CK CHECK(APLICA_PERIODO_PRUEBA IN('N','S'));
ALTER TABLE GPT_TIPOS_CONTRATO_LABORAL ADD CONSTRAINT TIPOS_CONTR_DURACFIJA_CK CHECK(ES_DURACION_FIJA IN('N','S'));


/**************************************************************************************************************************************
* Creacion de Constraints para tabla GPT_CONTRATOS_LABORALES
**************************************************************************************************************************************/
ALTER TABLE GPT_CONTRATOS_LABORALES ADD CONSTRAINT CONTRATOS_LABORALES_PK PRIMARY KEY (ID_CONTRATO);
ALTER TABLE GPT_CONTRATOS_LABORALES ADD CONSTRAINT CONTRAT_EMPRESA_FK FOREIGN KEY (ID_EMPRESA) REFERENCES MATCENTRAL.MAT_EMPRESAS (ID_EMPRESA) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GPT_CONTRATOS_LABORALES ADD CONSTRAINT CONTRAT_EMPLEADO_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES MATCENTRAL.MAT_TERCEROS (ID_TERCERO) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GPT_CONTRATOS_LABORALES ADD CONSTRAINT CONTRAT_CARGO_FK FOREIGN KEY (ID_CARGO) REFERENCES GPT_CARGOS (ID_CARGO) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GPT_CONTRATOS_LABORALES ADD CONSTRAINT CONTRAT_MOTIVOTERM_FK FOREIGN KEY (ID_MOTIVO_TERMINACION) REFERENCES GPT_MOTIVOS_TERMINAC_CONTRATO (ID_MOTIVO_TERMINACION) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GPT_CONTRATOS_LABORALES ADD CONSTRAINT CONTRAT_TIPO_FK FOREIGN KEY (ID_TIPO_CONTRATO) REFERENCES GPT_TIPOS_CONTRATO_LABORAL (ID_TIPO_CONTRATO) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GPT_CONTRATOS_LABORALES ADD CONSTRAINT CONTRAT_ESVIGENT_CK CHECK(ES_VIGENTE IN('N','S'));
ALTER TABLE GPT_CONTRATOS_LABORALES ADD CONSTRAINT CONTRAT_ESSAL_INTEGR_CK CHECK(ES_SALARIO_INTEGRAL IN('N','S'));
ALTER TABLE GPT_CONTRATOS_LABORALES ADD CONSTRAINT CONTRAT_DERECH_RECARG_CK CHECK(DERECHO_RECARGOS IN('N','S'));
ALTER TABLE GPT_CONTRATOS_LABORALES ADD CONSTRAINT CONTRAT_REPORTT_RECARG_CK CHECK(REPORTA_TIEMPO IN('N','S'));
/* ALTER TABLE GPT_CONTRATOS_LABORALES ADD CONSTRAINT CONTRAT_TIPOTERMINO_CK CHECK(DERECHO_RECARGOS IN('FIJO','INDEFINIDO')); */


/**************************************************************************************************************************************
* Creacion de Constraints para tabla GPT_PROVEEDORES
**************************************************************************************************************************************/
ALTER TABLE GPT_PROVEEDORES ADD CONSTRAINT PROVEEDORES_PK PRIMARY KEY (ID_PROVEEDOR);
ALTER TABLE GPT_PROVEEDORES ADD CONSTRAINT PROVEED_IDTERC_FK FOREIGN KEY (ID_PROVEEDOR) REFERENCES MATCENTRAL.MAT_TERCEROS (ID_TERCERO) ON UPDATE NO ACTION ON DELETE NO ACTION;


/**************************************************************************************************************************************
* Creacion de Constraints para tabla GPT_CLIENTES
**************************************************************************************************************************************/
ALTER TABLE GPT_CLIENTES ADD CONSTRAINT CLIENTES_PK PRIMARY KEY (ID_CLIENTE);
ALTER TABLE GPT_CLIENTES ADD CONSTRAINT CLIENT_IDTERC_FK FOREIGN KEY (ID_CLIENTE) REFERENCES MATCENTRAL.MAT_TERCEROS (ID_TERCERO) ON UPDATE NO ACTION ON DELETE NO ACTION;


/**************************************************************************************************************************************
* Creacion de Constraints para tabla GPT_PERIODO_LIQUID_NOMINA
**************************************************************************************************************************************/
ALTER TABLE GPT_PERIODO_LIQUID_NOMINA ADD CONSTRAINT PERIODO_LIQUID_NOMINA_PK PRIMARY KEY (ID_PERIODO_NOMINA);
ALTER TABLE GPT_PERIODO_LIQUID_NOMINA ADD CONSTRAINT PERINOMI_EMPR_FK FOREIGN KEY (ID_EMPRESA) REFERENCES MATCENTRAL.MAT_EMPRESAS (ID_EMPRESA) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GPT_PERIODO_LIQUID_NOMINA ADD CONSTRAINT PERINOMI_EMPRFEC_UK UNIQUE(ID_EMPRESA,COD_TIPO_PERIODO_NOMINA,FEC_INICIO_PERIODO,FEC_FIN_PERIODO);
ALTER TABLE GPT_PERIODO_LIQUID_NOMINA ADD CONSTRAINT PERINOMI_RANGFECHAS_CK CHECK (FEC_INICIO_PERIODO < FEC_FIN_PERIODO);
ALTER TABLE GPT_PERIODO_LIQUID_NOMINA ADD CONSTRAINT PERINOMI_TIPOPERIO_CK CHECK (COD_TIPO_PERIODO_NOMINA IN('SEMANAL','QUINCENAL', 'MENSUAL'));
ALTER TABLE GPT_PERIODO_LIQUID_NOMINA ADD CONSTRAINT PERINOMI_ESLIQUID_CK CHECK (ES_LIQUIDADO IN('N','S'));


/**************************************************************************************************************************************
* Creacion de Constraints para tabla GPT_REPORTE_TIEMPO
**************************************************************************************************************************************/
ALTER TABLE GPT_REPORTE_TIEMPO ADD CONSTRAINT REPORTE_TIEMPO_PK PRIMARY KEY (ID_PERIODO_NOMINA,ID_EMPLEADO,FECHA);
ALTER TABLE GPT_REPORTE_TIEMPO ADD CONSTRAINT REPORTMP_PERIODO_FK FOREIGN KEY (ID_PERIODO_NOMINA) REFERENCES GPT_PERIODO_LIQUID_NOMINA (ID_PERIODO_NOMINA) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GPT_REPORTE_TIEMPO ADD CONSTRAINT REPORTMP_EMPLEADO_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES MATCENTRAL.MAT_TERCEROS (ID_TERCERO) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE GPT_REPORTE_TIEMPO ADD CONSTRAINT REPORTMP_RANGOHORA_CK CHECK(HORA_ENTRADA < HORA_SALIDA);
ALTER TABLE GPT_REPORTE_TIEMPO ADD CONSTRAINT REPORTMP_ESTURNO_CK CHECK(ES_TURNO IN('N','S'));
ALTER TABLE GPT_REPORTE_TIEMPO ADD CONSTRAINT REPORTMP_TIPTURNO_CK CHECK(COD_TIPO_TURNO IN('DIURNO','NOCTURNO'));
ALTER TABLE GPT_REPORTE_TIEMPO ADD CONSTRAINT REPORTMP_ESDESC_CK CHECK(ES_DESCANSO IN('N','S'));
