/**************************************************************************************************************************************
 * Insercion de datos semilla en la tabla GPT_MOTIVOS_TERMINAC_CONTRATO
 **************************************************************************************************************************************/
INSERT INTO GPT_MOTIVOS_TERMINAC_CONTRATO(NOMBRE,DESCRIPCION,OBLIGA_INDEMNIZACION,USUARIO_CREACION,FEC_CREACION) 
VALUES('CUMPLIMIENTO DEL TERMINO', 'CUMPLIMIENTO DEL TERMINO', 'N','superadmin',CURRENT_TIMESTAMP);
INSERT INTO GPT_MOTIVOS_TERMINAC_CONTRATO(NOMBRE,DESCRIPCION,OBLIGA_INDEMNIZACION,USUARIO_CREACION,FEC_CREACION) 
VALUES('RENUNCIA VOLUNTARIA', 'RENUNCIA VOLUNTARIA', 'S','superadmin',CURRENT_TIMESTAMP);
INSERT INTO GPT_MOTIVOS_TERMINAC_CONTRATO(NOMBRE,DESCRIPCION,OBLIGA_INDEMNIZACION,USUARIO_CREACION,FEC_CREACION) 
VALUES('DESPIDO', 'DESPIDO', 'N','superadmin',CURRENT_TIMESTAMP);
INSERT INTO GPT_MOTIVOS_TERMINAC_CONTRATO(NOMBRE,DESCRIPCION,OBLIGA_INDEMNIZACION,USUARIO_CREACION,FEC_CREACION) 
VALUES('FALLECIMIENTO', 'FALLECIMIENTO', 'N','superadmin',CURRENT_TIMESTAMP);

/**************************************************************************************************************************************
 * Insercion de datos semilla en la tabla MAT_PARAMETROS_CONFIG
 **************************************************************************************************************************************/
INSERT INTO MAT_PARAMETROS_CONFIG(COD_PARAM_CONFIG,COD_APLICACION,DESCRIPCION,VLR_NUMERICO,VLR_CADENA,USUARIO_CREACION,FEC_CREACION)
VALUES('SALARO_MINIMO_VIGENTE','GESTPYMESOC','Valor del Salario minimo para el anio en vigencia',689454,NULL,'superadmin',CURRENT_TIMESTAMP);
INSERT INTO MAT_PARAMETROS_CONFIG(COD_PARAM_CONFIG,COD_APLICACION,DESCRIPCION,VLR_NUMERICO,VLR_CADENA,USUARIO_CREACION,FEC_CREACION)
VALUES('UVT_VIGENTE','GESTPYMESOC','Valor del UVT para el anio en vigencia',29753,NULL,'superadmin',CURRENT_TIMESTAMP);
INSERT INTO MAT_PARAMETROS_CONFIG(COD_PARAM_CONFIG,COD_APLICACION,DESCRIPCION,VLR_NUMERICO,VLR_CADENA,USUARIO_CREACION,FEC_CREACION)
VALUES('RUTA_BASE_RECURSOS_APP','GESTPYMESOC','Ruta local base dentro del servidor, en donde la aplicacion obtendra recursos, archivos, logos y configuracion',NULL,'/opt/GestPymeSOC/','superadmin',CURRENT_TIMESTAMP);
INSERT INTO MAT_PARAMETROS_CONFIG(COD_PARAM_CONFIG,COD_APLICACION,DESCRIPCION,VLR_NUMERICO,VLR_CADENA,USUARIO_CREACION,FEC_CREACION)
VALUES('DIRECTORIO_RECURSOS_APP','GESTPYMESOC','Nombre del directorio dentro del cual la aplicacion obtendra recursos estaticos, pj: foto de empleados, etc',NULL,'recursos/','superadmin',CURRENT_TIMESTAMP);
INSERT INTO MAT_PARAMETROS_CONFIG(COD_PARAM_CONFIG,COD_APLICACION,DESCRIPCION,VLR_NUMERICO,VLR_CADENA,USUARIO_CREACION,FEC_CREACION)
VALUES('DIRECTORIO_CONFIG_APP','GESTPYMESOC','Nombre del directorio dentro del cual la aplicacion obtendra archivos deconfiguracion',NULL,'config/','superadmin',CURRENT_TIMESTAMP);
INSERT INTO MAT_PARAMETROS_CONFIG(COD_PARAM_CONFIG,COD_APLICACION,DESCRIPCION,VLR_NUMERICO,VLR_CADENA,USUARIO_CREACION,FEC_CREACION)
VALUES('DIRECTORIO_DOWNLOADS_APP','GESTPYMESOC','Nombre del directorio dentro del cual la aplicacion almacenara de forma temporal archivos generados para descarga',NULL,'descargas/','superadmin',CURRENT_TIMESTAMP);
INSERT INTO MAT_PARAMETROS_CONFIG(COD_PARAM_CONFIG,COD_APLICACION,DESCRIPCION,VLR_NUMERICO,VLR_CADENA,USUARIO_CREACION,FEC_CREACION)
VALUES('DIRECTORIO_LOGOS_APP','GESTPYMESOC','Nombre del directorio dentro del cual la aplicacion obtendra logos',NULL,'logos/','superadmin',CURRENT_TIMESTAMP);

INSERT INTO GPT_DUAL VALUES('X');
